version: "3.7"

networks:
    laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    init: true
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    init: true
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["php-fpm"]
    depends_on:
        - mysql
        - redis
    networks:
      - laravel
  mysql:
    image: mysql:5.7
    container_name: mysql
    init: true
    restart: unless-stopped
    tty: true
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: takeaway
      MYSQL_PASSWORD: my_db_secret
      MYSQL_ROOT_PASSWORD: root_secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  redis:
    image: redis:alpine
    container_name: redis
    init: true
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379" 
    networks:
      - laravel
